
package soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CaseSoap", targetNamespace = "http://soap.webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CaseSoap {


    /**
     * 
     * @return
     *     returns java.util.List<soap.Case>
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCase", targetNamespace = "http://soap.webservice/", className = "soap.GetAllCase")
    @ResponseWrapper(localName = "getAllCaseResponse", targetNamespace = "http://soap.webservice/", className = "soap.GetAllCaseResponse")
    public List<Case> getAllCase()
        throws ParseException_Exception
    ;

    /**
     * 
     * @param mycase
     */
    @WebMethod
    @RequestWrapper(localName = "updateCase", targetNamespace = "http://soap.webservice/", className = "soap.UpdateCase")
    @ResponseWrapper(localName = "updateCaseResponse", targetNamespace = "http://soap.webservice/", className = "soap.UpdateCaseResponse")
    public void updateCase(
        @WebParam(name = "mycase", targetNamespace = "")
        Case mycase);

    /**
     * 
     * @param id
     * @return
     *     returns soap.Case
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCaseById", targetNamespace = "http://soap.webservice/", className = "soap.GetCaseById")
    @ResponseWrapper(localName = "getCaseByIdResponse", targetNamespace = "http://soap.webservice/", className = "soap.GetCaseByIdResponse")
    public Case getCaseById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
